import pynput, time, subprocess, sys
from pynput.keyboard import Key, Controller

def process_exists(process_name):
    call = 'TASKLIST', '/FI', 'imagename eq %s' % process_name
    # use buildin check_output right away
    output = subprocess.check_output(call).decode()
    # check in last line for process name
    last_line = output.strip().split('\r\n')[-1]
    # because Fail message could be translated
    return last_line.lower().startswith(process_name.lower())

keyboard = Controller()


def willy(n):
    x = int(n/2) + 0.75
    print("x")
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    time.sleep(0.75)
    while x>0:
        forza()
        keyboard.press(Key.left)
        print("left")
        keyboard.release(Key.left)
        time.sleep(0.2)
        x=x-1
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    time.sleep(0.75)
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    print("waits 7")
    time.sleep(7)
    forza()
    keyboard.press(Key.esc)
    print("esc")
    keyboard.release(Key.esc)
    time.sleep(1)
    forza()
    keyboard.press(Key.left)
    print("left")
    keyboard.release(Key.left)
    time.sleep(0.1)
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    time.sleep(0.75)
    forza()
    keyboard.press(Key.right)
    print("right")
    keyboard.release(Key.right)
    time.sleep(0.1)
    forza()
    keyboard.press(Key.right)
    print("right")
    keyboard.release(Key.right)
    time.sleep(0.1)
    forza()
    keyboard.press(Key.down)
    print("down")
    keyboard.release(Key.down)
    time.sleep(0.1)
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    time.sleep(1)
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    time.sleep(0.6)
    forza()
    keyboard.press(Key.down)
    print("down")
    keyboard.release(Key.down)
    time.sleep(0.5)
    forza()
    keyboard.press(Key.right)
    print("right")
    keyboard.release(Key.right)
    time.sleep(0.5)
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    time.sleep(0.6)
    forza()
    keyboard.press(Key.up)
    print("up")
    keyboard.release(Key.up)
    time.sleep(0.5)
    forza()
    keyboard.press(Key.enter)
    print("enter")
    keyboard.release(Key.enter)
    time.sleep(0.6)
    forza()
    keyboard.press(Key.esc)
    print("esc")
    keyboard.release(Key.esc)
    time.sleep(0.75)
    forza()
    keyboard.press(Key.esc)
    print("esc")
    keyboard.release(Key.esc)
    time.sleep(1)
    forza()
    keyboard.press(Key.right)
    print("right")
    keyboard.release(Key.right)
    time.sleep(0.75)

def forza():
    if process_exists('ForzaHorizon5.exe'):
        return 1
    else:
        sys.exit("eroare")
        #keyboard.press(Key.cmd_l)
        #keyboard.release(Key.cmd_l)
        #time.sleep(1)
        #keyboard.press('f')
        #keyboard.release('f')
        #time.sleep(1)
        #keyboard.press(Key.enter)
        #keyboard.release(Key.enter)
        #time.sleep(20)
        #print("alt")
        #keyboard.press(Key.alt_l)
        #time.sleep(0.1)
        #keyboard.press(Key.enter)
        #time.sleep(0.3)
        #keyboard.release(Key.enter)
        #time.sleep(0.1)
        #keyboard.release(Key.alt_l)
        #time.sleep(30)
        #print("30")
        #keyboard.press(Key.enter)
        #keyboard.release(Key.enter)
        #time.sleep(1)
        #keyboard.press(Key.enter)
        #keyboard.release(Key.enter)
        #time.sleep(1)
        #keyboard.press(Key.enter)
        #keyboard.release(Key.enter)
        #time.sleep(1)
        #time.sleep(20)
        #keyboard.press(Key.esc)
        #keyboard.release(Key.esc)
        #print("test")


while 69:
    n = int(input("introduceti nr de willy uri"))
    print("waits 5")
    time.sleep(5)
    for i in range(0,n):
        willy(i)
    break